# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('phone_number', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('currency', models.TextField()),
            ],
        ),
    ]
