# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mozioapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Provider',
        ),
        migrations.AddField(
            model_name='polygon',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mozioapp.Provider'),
        ),
    ]
