# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 01:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mozioapp', '0002_auto_20160602_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='name',
            field=models.TextField(default=datetime.datetime(2016, 6, 3, 1, 2, 44, 583000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
