# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mozioapp', '0003_polygon_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.TextField()),
                ('lon', models.TextField()),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mozioapp.Polygon')),
            ],
        ),
    ]
